apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qvwdflrrq-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/qvwdflrrq-java-quarkus-gitops